filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "childcare-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "childcare-logs"
setup.template.pattern: "childcare-logs-*"